### ISSUE TITLE
可以封装一个表单的form组件吗？类似vant里面的van-form

### ISSUE THREAD

**Issue by jiaoxiaoyuan** [ibestservices/ibest-ui#1]
可以封装一个表单的form组件吗？类似vant里面的van-form
![image](https://github.com/ibestservices/ibest-ui/assets/25316619/d3aca625-ba19-49ed-a636-cd83042d6e74)

**Comment by 542154968** [comment]
这个在计划里了 等输入框组件写出来就基本上能当表单用了  https://ibestui.ibestservices.com/guide/interation-plan/  但是这个实现起来内容有点多

**Comment by jiaoxiaoyuan** [comment]
好的，期待。

**Comment by 542154968** [comment]
已经开发了 版本审核中 1.10.0版本发布

**Comment by jiaoxiaoyuan** [comment]
![image](https://github.com/user-attachments/assets/2af93f15-db72-4f7b-8bd8-f9573991d5e2)

这是什么原因？

**Comment by damengbuxing** [comment]
@jiaoxiaoyuan 可以进群提问题
