### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by KassyTan95** [ibestservices/ibest-ui#14]
![image](https://github.com/user-attachments/assets/b47a7368-01fe-43f7-b4cd-196030079926)
![image](https://github.com/user-attachments/assets/ee55634e-2817-4fe4-a439-9f15f7d065fc)

**Comment by KassyTan95** [comment]
SDK 11  请问这是什么问题

**Comment by KassyTan95** [comment]
sdk11 请问这是什么问题导致的

**Comment by 542154968** [comment]
和sdk没关系 看着是文件名大小写的问题 v1.12.1版本修复了
