### ISSUE TITLE
引入包，初始化就报错了

### ISSUE THREAD

**Issue by houqiangxie** [ibestservices/ibest-ui#20]
![Snipaste_2024-10-24_16-39-52](https://github.com/user-attachments/assets/16169a99-c7fc-443a-ba35-54aaf5044bd2)

**Comment by damengbuxing** [comment]
请提供初始化和使用的代码截图, 方便的话可以进群 953492584 方便沟通

**Comment by houqiangxie** [comment]
> 请提供初始化和使用的代码截图, 方便的话可以进群 953492584 方便沟通

![image](https://github.com/user-attachments/assets/1628b624-3485-4de0-be3b-3924ff7e7f82)

**Comment by damengbuxing** [comment]
请提供下sdk版本

**Comment by houqiangxie** [comment]
> 请提供下sdk版本
api 12

**Comment by damengbuxing** [comment]
截个图看下呢, 因为openBindSheet12+为API12+的方法, 按图上报错是说 openBindSheet不在 UIContext 上, 应该是sdk版本问题,建议升级一下

**Comment by houqiangxie** [comment]
> 截个图看下呢, 因为openBindSheet12+为API12+的方法, 按图上报错是说 openBindSheet不在 UIContext 上, 应该是sdk版本问题,建议升级一下

![image](https://github.com/user-attachments/assets/7c6637df-e26e-4a03-b405-29640c046db2)

**Comment by damengbuxing** [comment]
是sdk问题, 现在都已经 5.0.0.71 了
