### ISSUE TITLE
作者您好，非常看好这个项目，现在鸿蒙UI组件库几乎没有，官方的组件难用，请问有组件开发TODO List 吗？

### ISSUE THREAD

**Issue by zhuyuanmin** [ibestservices/ibest-ui#22]
看了您当前开发完的组件，我觉得还有以下组件需要及时能更新：

- [] Icon 图标
- [] Tabbar 标签栏
- [] Popover 气泡弹出框
- [] Skeleton 骨架屏
- [] Progress 进度条
- [] Indicator 指示器
- [] Swiper 轮播
- [] Table 表格
- [] List & VirtualList  虚拟列表

如果有需要，我们可以提供开发贡献

**Comment by zhuyuanmin** [comment]
另外，由于鸿蒙已经支持开发桌面端了，UI组件库是不是还可以考虑适配PC组件呢？

**Comment by damengbuxing** [comment]
目前是依照vant的组件列表顺序来写, 有些得看组件封装出来用的方不方便,或者组件好不好封装

**Comment by 542154968** [comment]
欢迎贡献~

**Comment by damengbuxing** [comment]
@sunshinego12138 看到了加下qq群: 953492584, icon组件已发布

**Comment by damengbuxing** [comment]
@sunshinego12138 看到了加下qq群: 953492584, icon组件已发布

**Comment by sunshinego12138** [comment]
> @sunshinego12138 看到了加下qq群: 953492584, icon组件已发布

已加
