### ISSUE TITLE
兼容openharmony吗

### ISSUE THREAD

**Issue by fyt135** [ibestservices/ibest-ui#25]
兼容openharmony吗

**Comment by 542154968** [comment]
openharmony一般来说会比较新 我们跟着发布的大众版本走

**Comment by fyt135** [comment]
> openharmony一般来说会比较新 我们跟着发布的大众版本走

这个发布的大众版本是指harmonyos，还是指openharmony的release版本

**Comment by 542154968** [comment]
跟着鸿蒙官方文档的版本走 https://developer.huawei.com/
