### ISSUE TITLE
IBestToast 多次showLoading并hide，不会完全隐藏

### ISSUE THREAD

**Issue by QiaoMaomao** [ibestservices/ibest-ui#27]
更新到1.17.1后，两个接口同时使用IBestToast的showLoading会展示2个loading，第二次hide不起作用，loading一直展示，之前版本没有这个问题

**Comment by 542154968** [comment]
收到 先排查下

**Comment by 542154968** [comment]
我看了这这次版本改动这个组件只删了两行代码 应该是之前就有的问题

**Comment by QiaoMaomao** [comment]
那应该是我太久没更新了，昨天刚好更新了

**Comment by damengbuxing** [comment]
此问题会在1.18.0版本修复, 感谢你的issue, 欢迎加入qq群  953492584
