### ISSUE TITLE
预览报错

### ISSUE THREAD

**Issue by 2415383726** [ibestservices/ibest-ui#30]
请问，我拉取最新版的代码，点击entry的index页面预览会报错，是为什么呢？

![image](https://github.com/user-attachments/assets/c05b5954-c197-4d67-bab9-f07b0c4aec9c)

![image](https://github.com/user-attachments/assets/f8e4461c-508c-426b-aaab-053827fb4b74)

**Comment by damengbuxing** [comment]
组件库内部使用的部分api属性不支持预览器,请用模拟器预览
